/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import domaimodel.BaoHanh;
import domaimodel.ChiTietHoaDon;
import domaimodel.SanPham;
import domaimodel.chitiethoadonNoEmbe;
import java.rmi.server.ObjID;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import respon.BaoHanhRes;
import utility.JframeCheck;

/**
 *
 * @author Admin
 */
public class ChiTietBH extends javax.swing.JFrame {

    public DefaultTableModel dtm = new DefaultTableModel();
    private final JframeCheck jcheck = new JframeCheck();
    private SanPham sanpham;
    private List<Object> listcthd;

    /**
     * Creates new form ChiTietBH
     */
    public ChiTietBH() {
        initComponents();
    }

    public ChiTietBH(List<Object> lisst) {
        initComponents();
        listcthd = lisst;
        loadTableSP(lisst);
    }

    public void loadTableSP(List<Object> l) {
        dtm = (DefaultTableModel) tbHienSP.getModel();
        dtm.setRowCount(0);
        for (Object sanPham : l) {
            dtm.addRow(((chitiethoadonNoEmbe) sanPham).toRowhd1());
        }
    }
//    public BaoHanhView getAll(String dk){
//        BaoHanhView bh = new domaimodel.BaoHanhView(jcheck.createID().toString(), dk, ngayBH, dk, WIDTH, dk, SOMEBITS, ngayTra, cthd)
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbHienSP = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbHienSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã SP", "Tên SP", "Số lượng"
            }
        ));
        tbHienSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbHienSPMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbHienSP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void tbHienSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbHienSPMouseClicked

        String soLuong = JOptionPane.showInputDialog(this, "Số lượng");

        int soLuongReal = Integer.parseInt(soLuong);
        chitiethoadonNoEmbe cthd = (chitiethoadonNoEmbe) listcthd.get(tbHienSP.getSelectedRow());

        if (soLuongReal > cthd.getSoluong() || soLuongReal == 0) {
            JOptionPane.showMessageDialog(this, "Số lượng sản phẩm nhập vào phải bé hơn hoặc bằng số lượng đã mua");
            return;
        }

        new BaoHanhRes().add(new domaimodel.BaoHanh(jcheck.createID().toString(), jcheck.randomMA(), new Date(), null, 0, null,
                soLuongReal, null, cthd));

        DefaultTableModel dtm2 = (DefaultTableModel) BaoHanhView.tbhHienThiCTBH.getModel();
        dtm2.setRowCount(0);
        for (domaimodel.BaoHanh baoHanh : new BaoHanhRes().getALlBH()) {
            dtm2.addRow(baoHanh.toRowCTBH());
        }
    }//GEN-LAST:event_tbHienSPMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChiTietBH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChiTietBH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChiTietBH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChiTietBH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChiTietBH().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbHienSP;
    // End of variables declaration//GEN-END:variables
}
